name: Cypress Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    DB_HOST: localhost
                    DB_USER: root
                    DB_DATABASE: nodelogin
                    DB_PORT: 3306
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Start local server
              run: npm run start:server &

            - name: Wait for server to start
              run: sleep 10

            - name: Run Cypress tests
              run: npm run cy:run

            - name: Stop local server
              run: pkill node

            - name: Upload Cypress videos and screenshots
              if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: cypress-artifacts
                  path: cypress/videos/**/*,cypress/screenshots/**/*
